### ISSUE TITLE
PN-Support Datein

### ISSUE THREAD

**Issue by Zoey2936** [glitchbot-team/dashboard#2]
Über den PN Support können nur Bilder und Nachrichten versendet werden, aber keine Datein anderer Arten, z.b. pdf, txt, docx usw. Antwort Funktion von Discord wird auch nicht übertragen, wird aber wahrscheinlich auch nicht möglich sein.

**Comment by Zoey2936** [comment]
(Ich hab mir gerade erstmal nen Github account erstellt und hab noch keine ahnmung ob ich hier richtig bin)

**Comment by LucaGuth** [comment]
Dateien werden nun mit versendet 👍
Antwort Funktion mit senden nicht möglich
