### ISSUE TITLE
sl!faq funktioniert nicht

### ISSUE THREAD

**Issue by nkilders** [glitchbot-team/dashboard#3]
Bot macht nichts, wenn man den Befehl ausführt

**Comment by kaischallenberg** [comment]
Der Befehl ist zwar grade in der Help-Liste, ist aber noch nicht programmiert. Wir sammeln noch Fragen für diesen Befehl. Wenn du Vorschläge hast, kannst du die gerne auf unserem Discord in den passenden Channel posten. Wenn der Befehl im Bot ist, werden wir das mit in diese Issue schreiben.

**Comment by kaischallenberg** [comment]
Wurde mit dem neusten Beta Update hinzugefügt
