### ISSUE TITLE
Rechtschreibfehler auf der Website

### ISSUE THREAD

**Issue by ghost** [glitchbot-team/dashboard#4]
Auf der [slive-Website](https://slivebot.de/) befindet sich unten (unter dem Newsfeed) ein Rechtschreibfehler. 
"Comming soon..." wird mit einem "m" geschrieben, nicht mit 2.

![Screenshot_2021-01-12-16-02-41-26.jpg](https://user-images.githubusercontent.com/67111271/104331976-00f6f180-54f0-11eb-8119-5536a5b19513.jpg)

**Comment by olebohmbach** [comment]
@Natro-Kai

**Comment by LucaGuth** [comment]
Ich änders kurz warte
