### ISSUE TITLE
Ticket Öffentliche Benachrichtigung

### ISSUE THREAD

**Issue by DavidCraftDev** [glitchbot-team/dashboard#9]
Beim Beta Bot tretet beim Ticket System wieder der Bug auf das auch Leute die zum Channel eigentlich kein Zugriff haben eine Benachrichtigung bekommen und mit der dann zur Nachricht kommen ![image](https://user-images.githubusercontent.com/48714689/105580860-4092c880-5d8f-11eb-9a31-e022a41dfd34.png)

**Comment by kaischallenberg** [comment]
Nicht gesehen. An sich erstellen wir die Channels synchron zur Kategorie. Verstehe nicht, wie dann jeder Zugriff drauf hat. Muss sich @LubaLP mal drum kümmern

**Comment by DavidCraftDev** [comment]
![image](https://user-images.githubusercontent.com/48714689/112805418-dab80b00-9075-11eb-8048-db21965a0323.png)![image](https://user-images.githubusercontent.com/48714689/112805438-dee42880-9075-11eb-9941-9020692b026e.png)Ich möchte nochmal drauf hinweisen das der Bug immer noch besteht

**Comment by kaischallenberg** [comment]
Das Ticketsystem wird mit V2.2.0 vorübergehend deaktiviert. Wir werden uns ein neues System überlegen und es damit neu coden
